# Artifacts on intermediate per-commit build
name: Build Artifacts

on:
  # trigger it only on push
  push:
    paths:
      # track C#, .NET and VS files
      - "**.cs"
      - "**.csproj"
      - "**.sln"
    # only when pushing to master/main branch 
    branches: 
      - "master"
      - "main"

jobs:
  buildwin:
    runs-on: windows-latest
    steps:
    # just clone repo
    - name: Clone repository
      uses: actions/checkout@v3
    # setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    # restore nuget
    - name: Restore dependencies
      run: dotnet restore --nologo
      working-directory: SyrD.NET/
    # do build!
    - name: Build
      run: dotnet build -c Debug -o outs-win --nologo
      working-directory: SyrD.NET/
    # upload build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: SyrD.NET-Windows-Debug
        # A file, directory or wildcard pattern that describes what to upload
        path: SyrD.NET/outs-win
  buildlinux:
    runs-on: ubuntu-latest
    steps:
    # just clone repo
    - name: Clone repository
      uses: actions/checkout@v3
    # setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    # restore nuget
    - name: Restore dependencies
      run: dotnet restore --nologo
      working-directory: SyrD.NET/
    # do build!
    - name: Build
      run: dotnet build -c Debug -o outs-linux --nologo
      working-directory: SyrD.NET/
    # upload build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: SyrD.NET-Linux-Debug
        path: SyrD.NET/outs-linux
